### ISSUE TITLE
Решить проблему с переходом по кнопке "конвертик" в контактах Нашей команды

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#10]
Необходимо, чтобы при нажатии "конвертика":
* у пользователя автоматически открывался почтовый клиент с предложением написать письмо на данный e-mail. Поле "кому" предзаполнено.

**Comment by juljul81** [comment]
@Zoytz, Леш, посмотри, как лучше реализовать данную функцию?

**Comment by Zoytz** [comment]
Решено =)
