### ISSUE TITLE
Создать страницу Личный кабинет (Frontend)

### ISSUE THREAD

**Issue by vikseal** [hire-hire/hire-hire-front#13]
Страница с формой Личный кабинет содержит:

- Текст "Личный кабинет"
- Кнопку  “Выйти”  в хэдере

При нажатии на кнопку “Выйти” открывается попап c текстом: "Вы уверены, что хотите выйти?" и кнопками "Остаться" и "Выйти". При нажатии кнопки "Выйти", происходит переход на главную страницу под неавторизованным пользователем. Кнопка "Логин" пользователя в хэдере меняется на "Войти". При нажатии кнопки "Остаться", пользователь возвращается в личный кабинет.

https://www.figma.com/file/SLsP9UQstJOh4NYNj6GMY5/%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8?type=design&node-id=719-3060&t=TGnWyECOt1tzKQAX-4

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/14

**Comment by vikseal** [comment]
Баги от Кости:

Страница  ЛК: 
Логин в шапке обрезается по 7-й символ(при изменении разрешения количество символов меняется), должен по 10й
В адаптиве кнопка выйти вместо иконки

**Comment by Zoytz** [comment]
"Логин в шапке обрезается по 7-й символ(при изменении разрешения количество символов меняется), должен по 10й" - это от размера шрифта зависит (т.е. от дизайна), не от меня. Обрезается все, что не влезает в блок

https://github.com/hire-hire/hire-hire-front/pull/22
