### ISSUE TITLE
Добавить кнопку "Назад" на страницу с первым вопросом в ГИ

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#16]
На страницу Соревнования, где отражается первый вопрос в Голодных играх, добавить кнопку Назад.

При нажатии на кнопку "Назад" происходит переход на страницу выбора количества вопросов.

Данные, которые были введены на этой странице ранее, сохраняются (выбор категории, направления, имена игроков)

**Comment by Zoytz** [comment]
"Данные, которые были введены на этой странице ранее, сохраняются (выбор категории, направления, имена игроков)" - Не знаю как это сделать, вам нужен кто-то более опытный.

https://github.com/hire-hire/hire-hire-front/pull/22
