### ISSUE TITLE
Создать страницу с формой регистрации в новом дизайне (Frontend)

### ISSUE THREAD

**Issue by vikseal** [hire-hire/hire-hire-front#17]
Страницы с формой Регистрации в новом дизайне.

Адаптивная верстка - десктопные устройства (1920х1080, 1366х768), планшет (1024х768), мобильные телефоны (320х568).

- текст “Регистрация”
- поле для ввода логина (текст Логин) - обязательное поле для заполнения;
- поле для ввода пароля (текст Придумай пароль) - обязательное поле для заполнения;
- поле для повторного ввода пароля (текст Повтори пароль) - обязательное поле для заполнения.
- кнопка “Зарегистрироваться” (не активна до заполнения полей)

Справа от полей знак вопроса, при наведении всплывает тултип, который содержит описание ограничения поля. Как только заполнены все обязательные поля, кнопка “Зарегистрироваться” становится активной.
Как только заполнены все обязательные поля, кнопка "Зарегистрироваться" становится активной. При отсутствии или удалении информации из какого либо поля, кнопка снова должна стать не активной. 
При несоответствии поле, содержащее ошибку, выделяется красным и под ним высвечивается сообщение об ошибке.
При успешной регистрации пользователю присваивается уникальный ID, который сохраняется при следующих аутентификациях.
При успешной регистрации пользователь переходит на страницу личного кабинета (3.4)
Кнопка “Войти” в хэдере меняется на Логин пользователя.

Ошибки:

Логин:
а. подсвечивается красным поле "Логин" и текст "Логин не отвечает требованиям"
б. подсвечивается красным поле "Логин" и текст "Такой логин уже существует"

Придумай пароль
а. подсвечивается красным поле "Придумай пароль" и текст "Пароль не отвечает требованиям"
б. подсвечивается красным поле "Придумай пароль" и текст "Пароли не совпадают"

Повтори Пароль
б. подсвечивается красным поле "Повтори пароль" и текст "Пароль не отвечает требованиям"
в. подсвечивается красным поле "Повтори пароль" и текст "Пароли не совпадают"

Текст тултипа для логина:
Логин и пароль не должны совпадать. Требования к логину: от 2 до 25 символов,  прописные и строчные латинские буквы, цифры, знаки пунктуации ( _ - . , + ).

Логин может содержать:

- От 2 до 25 символов
- прописные и строчные латинские буквы
- цифры
- знаки пунктуации ( _ - . , + )
- без пробелов и иных символов.

Текст тултипа для пароля: 
От 8 до 40 символов, только латинские буквы, как минимум одна заглавная и строчная буква, как минимум одна цифра, только арабские цифры, без пробелов, другие допустимые символы - ~ ! ? @ # $ % ^ & * _ - + ( ) [ ] { } > < / \ | " ' . , : ;).

Пароль должен содержать:

- от 8 до 40 символов
- прописные и строчные латинские буквы
- цифры
- знаки пунктуации ( ` ~ ! @ # $ % ^ & * _ - + = [ ] \ { } | < > ? ’ " , . / )

**Comment by vikseal** [comment]
Zoytz

https://github.com/hire-hire/hire-hire-front/pull/11

Никита Кривошеев

[28 апр. 2023 г., 17:04]
валидацию катнул в тест, ветка https://github.com/Capwell/hire-hire/tree/validation2

**Comment by vikseal** [comment]
Костя Арсентьев_QA

[2 мая 2023 г., 7:02]
Так же в логине есть такой пункт:

прописные и строчные латинские буквы

Я ранее предлагал только нижний регистр использовать, еще раз предложу) так как разные регистры в будущем могут привести к путанице среди юзеров, если их понадобиться искать, т е :

User

user

USER

uSer

и т.д. это разные имена с системе

[2 мая 2023 г., 6:52]
В документе на диске написано к логину:

цифры,нижний слэш,точка,+,-, без пробелов и иных символов

В карточке здесь : знаки пунктуации ( _ - . , + )

Расхождение в запятой -ее можно использовать или нет ?

**Comment by vikseal** [comment]
Тестирование от Кости:

Не допустимы символы в пароле (которые разрешены)
В адаптиве видно кнопку выйти
Не отображаются ошибки с бека (типо имя уже занято)
Нету текста под кнопкой зарегистрироваться "Все поля обязательны для заполнения"
В дизайн системе при несовпадении пароля оба поля красные

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/22

**Comment by vikseal** [comment]
![image](https://github.com/hire-hire/hire-hire-front/assets/1682866/ce4a22d3-da46-4818-95c0-50d532daa8a9)

**Comment by vikseal** [comment]
Требования к полю пароль:

– пароль (ограничение к полю: прописные и строчные латинские буквы, символов min 8, max 40, цифры (но не должен состоять из одних цифр), спецсимволы, чувствительный к регистру). 
Логин и пароль не должны совпадать
