### ISSUE TITLE
Создать страницы с формой авторизации (Frontend)

### ISSUE THREAD

**Issue by vikseal** [hire-hire/hire-hire-front#18]
Страницы с формой Авторизации:

Адаптивная верстка - десктопные устройства (1920х1080, 1366х768), планшет (1024х768), мобильные телефоны (320х568)

текст “Войти”;
поле логин (с подписью Логин) - становится активным при нажатии;
поле пароль (с подписью Пароль) - становится активным при нажатии;
кнопка с текстом “Войти”, становится активной, когда поля логин и пароль заполнены.
текст “В первый раз здесь?”;
кнопка “Зарегистрироваться”. Не активна, подсвечивается при наведении. При нажатии кнопки “Зарегистрироваться” пользователь переходит на страницу "Форма регистрации" (3.3).
При вводе пользователем данных в поля логин и пароль (пользователь зарегистрирован) и нажатии кнопки “Войти”, происходит аутентификация. В случае, если данные корректны и пользователь аутентифицирован, он переходит на страницу личного кабинета. Кнопка “Войти” в хэдере меняется на Логин пользователя.

Если одно из полей/поля не заполнены, то они выделяются красным и под ним/ними высвечивается сообщение об ошибке “Введите логин/пароль”

Ошибки:
Если поле логин или пароль заполнены не верно:
Поля логин и пароль подсвечиваются красным и текст под полем пароль
"Неверный логин или пароль"

Ссылки:
Фич-лист п. 3.2: https://docs.google.com/spreadsheets/d/1whg8UL-h54ggIrrGDkm2n7GLyzSH4XKg/edit#gid=790568290

**Comment by vikseal** [comment]
Zoytz

https://github.com/hire-hire/hire-hire-front/pull/12

**Comment by vikseal** [comment]
Баги от Кости:

Страница  Вход: 
Не отображаются ошибки с бека (типо не верный логопас)
В адаптиве видна кнопка выйти

В шапке нету кнопки собеседование - так и должно быть.

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/22
