### ISSUE TITLE
сверстать страницу по предложке с успешной отправкой

### ISSUE THREAD

**Issue by KseniyaLV** [hire-hire/hire-hire-front#19]
Адаптивная верстка - десктопные устройства (1920 х 1080, 1366 х 768), планшет (1024 х 768), мобильные телефоны (320 х 568)
Страница содержит:
- текст 
Заголовок _"Предложи свой вопрос"_ 
если пользователь отправил 1 вопрос:
_"Спасибо за твой вклад, сегодня ты отправил (а) 1 вопрос из 10! Мы проверим вопросы и добавим их в свою базу"_
Количество вопросов зависит от количества отправленных форм (предложенных вопросов) в течение суток. (пользователь отправил 5 форм -  значит здесь текст будет _"Спасибо за ваш вклад, сегодня вы отправили 5 вопрос из 10! Мы проверим ваши вопросы и добавим их в свою базу"_
- кнопка "На главную"
- кнопка "Предложить новый вопрос"
В случае, если предложено 10 вопросов из 10 за сутки, то эта кнопка не отображается на данной странице и выводится текст 
_"Спасибо за твой вклад, сегодня ты отправил(а) 10 вопрос из 10! Пожалуй, на сегодня хватит, возвращайся завтра. Мы проверим вопросы и добавим их в свою базу"_

макеты - https://www.figma.com/file/SLsP9UQstJOh4NYNj6GMY5/%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8?type=design&node-id=1078-4498&t=2RFJR7Z9v6EXL3kn-4

**Comment by XeniaSheyk** [comment]
**Воспроизводит баг:**

**При успешной отправке более одного вопроса не меняется текст на количество отправленных пользователем вопросов, если отправляешь сразу несколько вопросов в Предложить вопрос**

 1. Перейти на страницу "Предложить вопрос"
 2. Выбрать опции
 3.  Валидно заполнить поля Вопрос, Ответ
 4.  Нажать отправить вопрос
 5. Видим текст "Спасибо за твой вклад, сегодня ты отправил (а) 1 вопрос из 10! Мы проверим вопросы и добавим их в свою базу"
 6. Нажать Предложить новый вопрос
 7. Задать 3 вопроса подряд через кнопку "Добавить еще вопрос"
 8. Нажать отправить вопрос


**ОР:** переход на форму с успешной отправкой с текстом равным количеству отправленных вопросов

**ФР:** переход на форму с успешной отправкой с текстом 

**Детали:** количество первых вопросов, их содержимое, выбор категории - не влияет на баг. У меня на видео должно было вывести 8. Один вопрос должен присутствовать, тогда воспроизводит 

https://github.com/hire-hire/hire-hire-front/assets/124672814/10489647-eb05-45e7-9b24-273e9f4707bc

**Comment by XeniaSheyk** [comment]
Количество задаваемых вопросов варьируется 
На тесте - 10, ок работает
