### ISSUE TITLE
Сверстать страницу по предложке

### ISSUE THREAD

**Issue by KseniyaLV** [hire-hire/hire-hire-front#20]
Адаптивная верстка - десктопные устройства (1920 х 1080, 1366 х 768), планшет (1024 х 768), мобильные телефоны (320 х 568)

**Страница "предложить вопрос"**
Страница содержит:

1. текст описания и правила 

Заголовок - Предложи свой вопрос
Текст: _Здесь у тебя есть возможность предложить нам свои варианты вопросов и ответов для наших пользователей.
Для взаимного удобства просим соблюдать наши простые правила:_

_- Вопрос должен быть понятным и конкретным. Представь, что такой вопрос задают тебе и ты понимаешь, что на него можно ответить. Всего ты можешь добавлять до 10 вопросов в день._

_- В поле «Ответ» введи ответ на тот вопрос, который ты задал ранее. Ответ также должен быть понятным, конкретным и исчерпывающим._

_- Мы тщательно проверяем информацию, которую получаем. После модерации твои вопросы и ответы на них попадут в нашу базу данных и помогут пользователям учиться и проверять свои знания._

_На данный момент доступна только подготовка к собеседованию по Python и Docker. 
Не расстраивайся, если это не то, что тебе нужно. Мы работаем над этим и в будущем добавим новые разделы._
  

2. блок вопроса, который содержит:

- номер вопроса, начиная с 1

- селект с выбором категории, на данный момент один - _Программирование_

- селект с выбором подкатегории, на данный момент два - _Python, Docker_

- поле "Вопрос" содержит:

     - текст "_Ввести вопрос_", который исчезает при заполнении поля

     - под полем счетчик с указанием заполненности поля (n/10-500, где n - количество введенных символов) 

     - тултип, содержащий информацию об ограничениях заполнения 

Валидация для полей "вопрос":
- обязательные к заполнению
- Буквы, цифры
- Русский, Английский
- минимальное количество символов - 10
- максимальное количество символов - 500
- Все спецсимволы

- поле "Ответ" -  содержит:

     - текст "_Ввести ответ_", который исчезает при заполнении поля

     - под полем счетчик с указанием заполненности поля (n/2-500, где n - количество введенных символов) 

     - тултип, содержащий информацию об ограничениях заполнения 

Валидация для полей "ответ":
- обязательные к заполнению
- Буквы, цифры
- Русский, Английский
- минимальное количество символов - 2
- максимальное количество символов - 500
- Все спецсимволы

3. Кнопка "Добавить вопрос"
4. Кнопка "Отправить вопрос"

При нажатии на кнопку "Добавить вопрос" появляется блок вопроса, аналогичный предыдущему, меняется номер вопроса (вопрос 1, вопрос 2 и т.д.)

максимальное количество отправляемых вопросов в сутки - 10
ссылка на макеты - https://www.figma.com/file/SLsP9UQstJOh4NYNj6GMY5/%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8?type=design&node-id=1038-3893&t=2RFJR7Z9v6EXL3kn-4

**Comment by XeniaSheyk** [comment]
- [x] **Отсутствует тултип**, содержащий информацию об ограничениях заполнения - на макете также отсутствует. Ошибка дизайна

- [x] Воспроизводит баг - **_пофиксили_**

**При заполнении ответ/вопрос пробелами отправляется пустая форма**

1. Перейти в блок предложить вопрос
2. Выбрать категорию
3. Выбрать направление
4. В поле вопрос и ответ ввести 10 пробелов

**ОР:** вопрос/ответ не отправляется, тк является пустым, поле - обязательное
**ФР:** вопрос/ответ отправляется. В БД не создается. Текст "Спасибо за твой вклад, сегодня ты отправил (а) 0 вопрос из 10!

https://github.com/hire-hire/hire-hire-front/assets/124672814/ea4c88a0-7f7a-47ee-8920-77e4b2418e1b

"

**Comment by XeniaSheyk** [comment]
- [x]  **При заполнении поля вопрос/ответ пропускает иероглифы** - **_не фиксим_**

1. Перейти в блок предложить вопрос
2. Выбрать категорию
3. Выбрать направление
4. В поле вопрос ввести 俄国山寨1俄国山寨俄国山寨1俄国山寨

**ОР:** система не пропускает другой алфавит, кроме русского и английского
**ФР:** система пропускает вопрос, вопрос попадает в БД

**Детали:** в поле ответ также пропускает иероглифы



![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/660b44ac-3c5f-4d59-a1ad-02285e3b4a4f)
![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/cd4608f2-81b8-4166-b518-56ea5aa591a4)
![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/31b8d8ff-9161-440a-bbaa-d216d7166ce7)

**Comment by XeniaSheyk** [comment]
- [x]  https://github.com/orgs/hire-hire/projects/1/views/9?pane=issue&itemId=32727746 - решим в отдельной задачке
2 символа в ответе
