### ISSUE TITLE
Сверстать фичу "Донаты" (Frontend)

### ISSUE THREAD

**Issue by Ser-Denisov** [hire-hire/hire-hire-front#23]
Адаптивная верстка - десктопные устройства (1920 х 1080, 1366 х 768), планшет (1024 х 768), мобильные телефоны (320 х 568)

Кнопка "ЗаДонатить".
Страница с выбором суммы доната.
Страница благодарности за донат.

Задача 1. Кнопка "ЗаДонать":
-Название кнопки содержит две большие буквы (как в название задачи).
-Кнопка "ЗаДонать" находится в хедере, вместо кнопки "Собеседование".
-После ее нажатия происходит переход на страницу с выбором суммы доната.

Задача 2. Страница с выбором суммы доната:
Страница содержит:

Хедер / футер.
Текст ЗаДонатить (сверху над блоком с текстом, по середине блока/страницы или на усмотрение дизайнера).
Размещен блок с текстом: "Спасибо, что интересуешься нашим проектом! Мы очень рады, что наша работа находит отклик в сердцах людей. Если хочешь поддержать наш проект, будем очень благодарны за любую помощь. Ты можете сделать пожертвование на развитие проекта. Твоя поддержка позволит нам оплачивать сервер, продолжать развиваться и мотивировать ребят, участвующих в проекте, делать наш мир лучше. Спасибо еще раз за твое участие!".
3 кнопки для выбора суммы доната: 100 р, 300р, 500р. Меняет цвет после ее нажатия.
Поле ввода любой суммы. Поле по умолчанию содержит текст "другая сумма", которая исчезает при заполнении. Имеет ограничения для ввода- только цифры, только целое число (1, 5, 10, 100), без копеек.  Вводимая сумма не должна начинаться с "0". Ограничения по кол-ву символов- минимальное 1 символ, максимальное 6 символов.
Справа от поля знак вопроса, при наведении всплывает тултип, который содержит описание ограничения поля. Текст ограничений: Для ввода суммы можно использовать только цифры. Сумма вводится без копеек" .
Кнопка "ЗаДонатить". Становится активной после выбора одного из вариантов суммы или ввода своей. При нажатии на нее осуществляется переход на страницу платежного сервиса ЮКасса.

Задача 3. Страница благодарности за донат.
Переход на нее осуществляется после прохождения процедуры оплаты в ЮКассе.
Страница содержит:

Хедер / футер
блок с теском благодарности: Спасибо, что ты с нами! Мы очень рады, что НаймиНайми находит отклик в сердцах людей. Твоя поддержка и донаты помогают нам развиваться и двигаться вперед. Спасибо, что веришь в нас и поддерживаешь наш труд. Мы ценим твое участие и будем продолжать работать над тем, чтобы сделать наш проект еще лучше и полезнее для всех..
кнопку "На главную страницу". Располагается после блока с текстом. При ее нажатии осуществляется переход на главную страницу сайта.

Ограничения по суммам оплаты от ЮКассы:
   1. Банковские карты:  
Visa, Mastercard, Maestro, Мир, JCB, American Express: минимум — 1 ₽, максимум — 350 000 ₽ (до 700 000р в месяц)
   
   2. Электронные деньги:
а) ЮMoney : минимум — 1 ₽, максимум — 250 000 ₽ (до 3 000 000р в месяц)
б) QIWI Wallet : Минимум — 1 ₽, максимум — 250 000 ₽
   
   3. Инвойсинг:
а) SberPay: Минимум — 1 ₽, максимум — 500 000 ₽
б) Тинькофф: Минимум — 1 ₽, максимум — 600 000 ₽
в) СБП: Минимум — 1 ₽, максимум — 500 000 ₽

Ссылка на макеты: https://www.figma.com/file/SLsP9UQstJOh4NYNj6GMY5/%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8%D0%9D%D0%B0%D0%B9%D0%BC%D0%B8?type=design&node-id=0-1&t=zyZpzGJVa2HfoLFX-0

**Comment by Ser-Denisov** [comment]
![Image](https://github.com/hire-hire/hire-hire-front/assets/132064809/9947d345-ca78-4104-8f9c-653b05dd3105)

окончательный вид макетов

**Comment by XeniaSheyk** [comment]
- [x]  **Воспроизводится баг** - _**пофиксили**_

**Стрелочки числового инпута отображаются в поле Другая сумма**

![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/a50867ba-0246-4871-9d91-d0f6f2dc66c8)

**Comment by XeniaSheyk** [comment]
- [x]  **При вводе символа в конце введенной суммы - можно ввести любое число следом без границ** - _**пофиксили**_

1. Перейти на страницу Донатов
2. Ввести 1000
3. Поставить знак - 
4. Продолжать вводить числа

**ОР:** система не принимает любые спецсимволы
**ФР:** система принимает спецсимвол, можно продолжать неограниченный набор

**Детали:** также проходит символ +
Если ставить перед всеми цифрами в диапазон чисел (1-6) Например, -1000/+1000 - кнопка Задонатить активна
Если ставить в середине и соблюсти диапазон чисел (1-6) Например, 100-0/ 100+1 - кнопка Задонатить не аквтина
Если ставить после чисел и соблюсти диапазон чисел (1-6) Например, 1000-/1000+ - можно вводить бесконечное значение, кнопка Задонатить не аквтина

![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/880cff4c-7448-46c0-a4d2-d7305b32d2e5)

**Comment by XeniaSheyk** [comment]
- [x]  В поле Другая сумма можно ввести точку -  _**пофиксили**_

1. Перейти на страницу Донатов
2. Ввести 122.

**ОР:** ввести точку нельзя
**ФР:** точка ставится, кнопка Задонатить не активна. При попытке поставить еще цифру точка пропадает


![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/d7db5f1f-ae4d-42f7-ad8e-3e2e1ddb018b)

**Comment by XeniaSheyk** [comment]
- [x]  **В поле Другая сумма можно ввести запятую** - _**пофиксили**_

1. Перейти на страницу Донатов
2. Ввести 122,

**ОР:** ввести запятую нельзя
**ФР:** запятая ставится, кнопка Задонатить активна, можно сделать донат. При попытке поставить еще цифру запятая пропадает



![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/dbe60f71-69dd-4b22-aaac-b2c4218d83d9)

**Comment by XeniaSheyk** [comment]
- [x]  **Копирование в поле Другая сумма** - **_пофиксили_**

1. Скопировать 2+-00
2. Вставить в поле Другая сумма

**ОР:** система не пропускает -+
**ФР:** система пропускает

![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/d054db08-8587-43fb-92ee-0b310ebf9d71)

**Comment by XeniaSheyk** [comment]
- [x]  **При наведении фокуса в поле и нажатии на клавиатуре стрелочек вверх/вниз появляются цифры в поле Другая сумма** - **_пофиксили_**

1. Нажать на поле Другая сумма
2. Нажать кнопку вверх стрелочка на клавиатуре

**ОР:** ничего не происходит
**ФР:** появляется цифра 1. Идет счет суммы

**Comment by XeniaSheyk** [comment]
- [x]  **Ручка callback возвращает на https://test-hire-hire/donation/callback/** **_- пофиксили_**

1. Быть на странице Донатов
2. Выбрать любую сумму
3. Поставить галочку в чекбокс Пользовательское соглашение
4. Нажать кнопку ЗаДонатить
5. Переход на Юкассу
6. Ввести там валидные данные карточки и сделать тестовый платеж
7. Нажать кнопку Вернуться на сайт

**ОР:** возвращаемся на https://test-hire-hire.proninteam.ru/donation/callback/
**ФР:** возвращаемся на https://test-hire-hire/donation/callback/. Отображается ошибка

![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/f7b871dd-aecd-477e-8ecc-1560a37e53a8)

**Comment by XeniaSheyk** [comment]
https://github.com/orgs/hire-hire/projects/1/views/9?pane=issue&itemId=34355395 - отдельная таска на баги АПИ

**Comment by XeniaSheyk** [comment]
- [x] **Сделать переход из страницы Благодарности на Главную в шапку** **_- пофиксили_**

**Comment by XeniaSheyk** [comment]
**Протестировано** 


![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/d18333ae-e9dd-4ab8-832d-0fb96e931a47)



![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/68e9f91a-9a11-4575-8472-ee0d4bc82fa8)
