### ISSUE TITLE
Добавить на страницу Соревнования кнопку "Завершить соревнование"

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#26]
Добавить кнопку "Завершить соревнование" на страницах Соревнования (со второй до предпоследней) на месте кнопки "Назад" (отражена на макете страницы 1/n).
При нажатии на кнопку "Завершить соревнование" дуэль прерывается и происходит переход на страницу Голодные игры с выбором категории, направления, количества вопросов и имен игроков.

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/25
