### ISSUE TITLE
Новая страница должна открываться сверху (в шапке) при выборе опции перехода из Главной страницы

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#41]
При переходе с Главной страницы на другие страницы сайта необходимо, чтобы страницы открывались сверху.

**Comment by XeniaSheyk** [comment]
**Предусловие:** авторизоваться под админом

1. Перейти на Главную страницу
2. Нажать в блоке Голодные игры "Провести на соревнования"

**ОР:** страница открывается сверху (с шапки). Информацию пользователь получает сверху вниз и скролом доходит до конца
**ФР:** страница открывается в Футере

**Окружение:** тест, прод 
 
**Детали:** воспроизводит при нажатии "Перейти" в Пройти собеседование, "Пройти соревнование" в Голодные игры, "Предложить свой вопрос" в Предложи свой вопрос и внутри этих поинтов. 
Норм наверх переходит только из Шапки
По юзабилити выглядит не очень удобно, можно не заметить, что сверху есть еще выбор категории, например

https://github.com/hire-hire/hire-hire-front/assets/124672814/34f956c7-8a48-4bf9-addd-2947820d9d14
