### ISSUE TITLE
В полях вопросы и ответы сделать корректный перенос слов (на проде)

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#47]
В полях "вопрос" или "правильный ответ" сделать, чтобы слова не прерывались при переносе на следующую строку.

**Comment by XeniaSheyk** [comment]
**Протестировано:**
**Предложи свой вопрос -**

 ![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/bbdaaef7-981b-4ff4-bddf-6272f345f04a)


**В ГИ -**

 ![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/979d4363-f8de-4c1e-b820-772f8f8280da)


**Раньше -** 

![Image](https://github.com/hire-hire/hire-hire-front/assets/124672814/c03e05fe-27fd-4bea-801d-3be7e5661875)
