### ISSUE TITLE
Страница Голодные игры (Frontend) новый дизайн

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#5]
Подготовить фронтенд страниц в новом дизайне (с незначительными корректировками - выделено ***жирным*** по тексту ниже):

Все страницы Голодные игры видны только под логином админа:

* страница выбора количества вопросов и игроков

* страница самого соревнования 

* страница с результатами соревнования

Осуществить передачу/получение данных на/от бэк:

* количество выбранных вопросов

* ввод имени игрока и отображение их в испытании

* счетчик вопросов

* тексты вопросов/правильных ответов

* счетчик результата в разрезе игроков/неправильных ответов

Адаптивная верстка - десктопные устройства (1920х1080, 1366х768), планшет (1024х768), мобильные телефоны (320х568).

### Страница выбора количества вопросов и игроков: 

При нажатии на кнопку "Провести соревнование" (на Главной странице), пользователь переходит на страницу с выбором количества вопросов и имен игроков
Страница содержит:
* текст "Голодные игры"
* текст "Категория и направление"
*  активное окно с фильтром и 1 вариант: программирование. Заголовок фильтра: "категория"
*  активное окно с фильтром и 3 варианта: "Python", "Docker", "все направления". Заголовок фильтра: "направление"
* активное окно с фильтром и 3 варианта "10 вопросов" (по умолчанию), "20 вопросов", "30 вопросов". Заголовок фильтра: "Количество вопросов"
* поле для ввода "Игрок 1", справа от поля вопросительный знак с тултипом, который содержит ограничения к полю
* поле для ввода "Игрок 2", справа от поля вопросительный знак с тултипом, который содержит ограничения к полю 
* кнопка "Далее" - активна при валидных данных имен игроков

***Добавить*** в Голодные игры напротив полей ввода имен игроков вопросительный знак с ***тултипом***, который содержит ограничения к полю. Текст для тултипа: ***от 2 до 20 символов, Ru/En, прописные и строчные буквы, Цифры, Пробел, -***

Ограничения/допущения: 
* Блок Голодный игры становится видимым конкретному пользователю, у которого есть логин/пароль админа
* Информация поступает из базы
* При выборе количества вопросов - ID  этих вопросов  прописывается к ID пользователя, чтобы в рамках этой и последующих сессий не повторяться.
* Когда авторизованный пользователь пройдет все вопросы, они будут повторяться. 
* Ограничения полей ввода имен игроков:  от 2 до 20 символов, Ru/En, прописные и строчные буквы, Цифры, Пробел, - 

### Страница "Соревнования" 

Страница содержит:
- текст "Соревнования"
- счетчик вопросов вида "Вопрос 1/n" (где n - количество выбранных вопросов)
- таблица с именами игроков и набранными очками
 - поле "Вопрос" с текстом вопроса 
 - поле "Правильный ответ". До нажатия кнопки "Показать правильный ответ" поле скрыто.
- текст "Кто ответил правильно"
- кнопки "игрок 1", "игрок 2", "нет правильного ответа" 
 - кнопка "Показать правильный ответ", при нажатии на нее появляется поле "правильный ответ" с текстом ответа, ,  кнопка "Следующий вопрос" становится активной.
 - на странице первого вопроса кнопка "Назад". При нажатии на кнопку "Назад" на странице с первым вопросом происходит переход на страницу выбора количества вопросов.

При нажатии на кнопку "Следующий вопрос" переход осуществляется к странице со следующим вопросом, сценарий повторяется до тех пор, пока не пройдены все вопросы, их количество пользователь выбрал на странице "Выбери количество вопросов".

После окончания прохождения выбранного количества вопросов, осуществляет переход на страницу "Результаты"  

Ограничения/допущения: 
* В зависимости от выбранного направления на предыдущем шаге, мы попадаем на соответствующую страницу с вопросами (Python, Docker или вопросы по всем направлениям)
* Картинка на странице соответствует выбранному направлению. Если выбрано все направления - картинка универсальная по Программированию.
* Текст вопроса рандомно поступает из базы данных
* Текст "Вопрос" и "Кто ответил правильно" - захардкожено
* Кнопки "Игрок 1", "Игрок 2", "нет правильного ответа" становятся активными после нажатия кнопки "Показать правильный ответ" . При нажатии на любую одну из них, кнопка становится отмеченной (выбранной), при следующем нажатии на другую кнопку отмеченной становится вновь выбранная, а с предыдущей отметка снимается. Таким образом, можно выбрать только 1 из 3 кнопок.  
* Кнопка "Показать следующий вопрос" становится активной после выбора, кто ответил правильно.
* Поле "Правильный ответ" с текстом ответа появляется после нажатия на кнопку "Показать правильный ответ"

### Страница с результатами соревнований:
Страница содержит:
- текст "Результаты"
- счетчик результата  с именами игроков и набранными ими очками
- счетчик неправильных ответов
- кнопка "На главную", при нажатии на нее мы возвращаемся на главную страницу
 - кнопка "Новое соревнование", при нажатии на нее переход на страницу  "Выбери количество вопросов" 

Ограничения/допущения:
* Информация поступает из базы
* Должен быть реализован счетчик ответов по каждому нажатию кнопки "игрок 1", "игрок 2", "неправильный ответ" по предыдущему блоку "Соревнования" и полученное значение для каждой кнопки выводится в соответствующее поле текущего блока.
* Картинка на странице соответствует выбранному направлению. Если выбрано все направления - картинка универсальная по Программированию

**Comment by Zoytz** [comment]
Без адаптива т.к. его нет.
https://github.com/hire-hire/hire-hire-front/pull/22

**Comment by juljul81** [comment]
Фон в поле "Правильный ответ" привести в соответствии с макетом

**Comment by juljul81** [comment]
На страницах Соревнования (по докеру и все категории) - добавить картинки. Для этого нужно картинки вставить в админку.

Данный вопрос закрыт.
