### ISSUE TITLE
Создать страницу с формой регистрации в новом дизайне (Frontend)

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#7]
Страницы с формой Регистрации в новом дизайне.

Бэку установить валидацию для логина и пароля в соответствии с требованиями (описаны ниже и п.3.3. фич-листа)

Адаптивная верстка - десктопные устройства (1920*1080, 1366*768), планшет (1024*768), мобильные телефоны (320*568).

* текст “Регистрация”
* поле для ввода логина (текст Логин) - обязательное поле для заполнения;
* поле для ввода пароля (текст Придумай пароль) - обязательное поле для заполнения;
* поле для повторного ввода пароля (текст Повтори пароль) - обязательное поле для заполнения.
* кнопка “Зарегистрироваться” (не активна до заполнения полей)

##### Чек-бокса нет

Справа от полей знак вопроса, при наведении всплывает тултип, который содержит описание ограничения поля. Как только заполнены все обязательные поля, кнопка “Зарегистрироваться” становится активной.

При успешной регистрации пользователь переходит на страницу личного кабинета (3.4)

Кнопка “Войти” в хэдере меняется на Логин пользователя.

Ошибки: 
1. Логин:  
а. подсвечивается красным поле "Логин" и текст "Логин не отвечает требованиям" 
б. подсвечивается красным поле "Логин" и текст "Такой логин уже существует" 
 
2. Придумай пароль 
а. подсвечивается красным поле "Придумай пароль" и текст "Пароль не отвечает требованиям" 
б. подсвечивается красным поле "Придумай пароль" и текст "Пароли не совпадают" 
 
3. Повтори Пароль 
б. подсвечивается красным поле "Повтори пароль" и текст "Пароль не отвечает требованиям" 
в. подсвечивается красным поле "Повтори пароль" и текст "Пароли не совпадают"

#### Текст тултипа для логина:

Для защиты ваших данных логин и пароль не должны совпадать. Логин может содержать:

* от 2 до 25 символов
* прописные и строчные латинские буквы
* цифры
* знаки пунктуации ( _ - . , + )
* без пробелов и иных символов.

#### Текст тултипа для пароля:

Для защиты ваших данных логин и пароль не должны совпадать. Пароль должен содержать:

* от 8 до 40 символов
* прописные и строчные латинские буквы
* цифры
* знаки пунктуации ( ` ~ ! @ # $ % ^ & * _ - + = [ ] \ { } | < > ? ’ " , . / )

**Comment by juljul81** [comment]
Костя Арсентьев_QA

[2 мая 2023 г., 7:02]
Так же в логине есть такой пункт:

прописные и строчные латинские буквы

Я ранее предлагал только нижний регистр использовать, еще раз предложу) так как разные регистры в будущем могут привести к путанице среди юзеров, если их понадобиться искать, т е :

User

user

USER

uSer

и т.д. это разные имена с системе

**Comment by juljul81** [comment]
Костя Арсентьев_QA

[2 мая 2023 г., 6:52]
В документе на диске написано к логину:

цифры,нижний слэш,точка,+,-, без пробелов и иных символов

В карточке здесь : знаки пунктуации ( _ - . , + )

Расхождение в запятой -ее можно использовать или нет ?

**Comment by juljul81** [comment]
Никита Кривошеев

[28 апр. 2023 г., 17:04]
валидацию катнул в тест, ветка https://github.com/Capwell/hire-hire/tree/validation2

**Comment by juljul81** [comment]
Никита Кривошеев

[26 апр. 2023 г., 15:57]
PR положил в аттач

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/11
