### ISSUE TITLE
Создать страницы с формой авторизации (Frontend)

### ISSUE THREAD

**Issue by juljul81** [hire-hire/hire-hire-front#8]
Страницы с формой Авторизации:

* страница с формой Авторизации
* страница с формой Авторизации с ошибкой

Адаптивная верстка - десктопные устройства (19201080, 1366768), планшет (1024768), мобильные телефоны (320568)

* текст “Войти”;
* поле логин (с подписью Логин) - становится активным при нажатии;
* поле пароль (с подписью Пароль) - становится активным при нажатии;
* кнопка с текстом “Войти”;
* текст “В первый раз здесь?”;
* кнопка “Зарегистрироваться”. Не активна, подсвечивается при наведении. При нажатии кнопки “Зарегистрироваться” пользователь переходит на страницу"Форма регистрации" (3.3).
* кнопка для закрытия страницы - при нажатии перенаправляет на главную страницу без сохранения изменений.

При вводе пользователем данных в поля логин и пароль (пользователь зарегистрирован) и нажатии кнопки “Войти”, происходит аутентификация. В случае, если данные корректны и пользователь аутентифицирован, он переходит на страницу личного кабинета. Кнопка “Войти” в хэдере меняется на Логин пользователя.

Ошибки (бэку обеспечить передачу на фронт по ошибкам, выделенным жирным):

* Если одно из полей/поля не заполнены, то они выделяются красным и под ним/ними высвечивается сообщение об ошибке “Введите логин/пароль”

* Если пользователь не зарегистрирован или Логин введен не корректно, при нажатии кнопки “Войти” поле подсвечивается красным и выводится сообщение “Аккаунт не найден. Повторите попытку или зарегистрируйтесь.”

* При некорректном вводе пароля и нажатии кнопки “Войти” поле подсвечивается красным и выводится сообщение “Введен некорректный пароль”.

Ссылки:
Фич-лист п. 3.2: https://docs.google.com/spreadsheets/d/1whg8UL-h54ggIrrGDkm2n7GLyzSH4XKg/edit#gid=790568290

**Comment by Zoytz** [comment]
https://github.com/hire-hire/hire-hire-front/pull/12
